### ISSUE TITLE
Severe console spam after updating to 2.1s

### ISSUE THREAD

**Issue by Recaran** [sci4me/Torcherino#20] opened 2015-05-06 08:21 UTC
Hey, since updating ive noticed a lot of console spam regarding the creation of a torcherino. Error in server log is as follows:

[10:20:36] [Server thread/ERROR]: A TileEntity torcherino_tile(com.sci.torcherino.tile.TileTorcherino) located @ 1038,71,1492 has thrown an exception during creation, it cannot be created. Report this to the mod author
java.lang.InstantiationException: com.sci.torcherino.tile.TileTorcherino
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_11]
	at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:108) [aor.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:525) [aqk.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:44) [ChunkIOProvider.class:git-Cauldron-MCPC-Plus-1.7.10-1.1381.06.221]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) [ChunkIOProvider.class:git-Cauldron-MCPC-Plus-1.7.10-1.1381.06.221]
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:git-Cauldron-MCPC-Plus-1.7.10-1.1381.06.221]
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:git-Cauldron-MCPC-Plus-1.7.10-1.1381.06.221]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:git-Cauldron-MCPC-Plus-1.7.10-1.1381.06.221]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:165) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:138) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:261) [ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:739) [ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:665) [ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:685) [ahb.class:?]
	at net.minecraft.block.BlockStaticLiquid.func_149674_a(BlockStaticLiquid.java:95) [ant.class:?]
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:562) [mt.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:276) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_11]
Caused by: java.lang.NoSuchMethodException: com.sci.torcherino.tile.TileTorcherino.<init>()
	at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_11]

**Comment by sci4me** [comment] 2015-05-10 17:45
I'm a derp. Will fix asap in next release.

**Comment by abdullamu** [comment] 2015-05-28 20:58
i have this problem too

**Comment by sci4me** [comment] 2015-05-28 21:27
I apologize for the inconvenience. This is a confirmed issue and will be fixed...

I also apologize, but I am unable to make time guarantees right now...

**Comment by LemonLake** [comment] 2015-05-29 10:56
I have a similar issue, but after a server update I can no longer recieve the error so I can't show you that, but if it has any relevance to this issue I am currently being spammed with:
`Skipping BlockEntity with id torcherino_tile`

**Comment by sci4me** [comment] 2015-05-29 15:19
@LemonLake yes, the reason is due to a lack of a constructor. I assume it would say skipping because it can't create the tile entity.

**Comment by sci4me** [comment] 2015-05-29 15:22
Can someone confirm if 8003d00fea3b11a8688128c7d38ea85e026c7f82 fixed this issue please?

**Comment by LemonLake** [comment] 2015-05-29 16:48
Makes sense, usually it has to instantiate the class instead of using createNewTileEntity in block when loading the world. I can't test at the moment as people are online on the server, so I will update the mod later. Do I have to update the client too?

**Comment by sci4me** [comment] 2015-05-29 17:26
Well, don't put it on the server yet... wait until we know if it's fixed.

**Comment by abdullamu** [comment] 2015-05-29 20:06
it seems to be fixed not showing this spam i hope it fixes the rest of the torcherino when the chunk the torcherino in get unloaded torcherino losses its settings

**Comment by LemonLake** [comment] 2015-05-29 20:17
That is probably the same issue, so it should be fixed

**Comment by sci4me** [comment] 2015-05-30 01:18
@LemonLake that's probably right... If someone can confirm (just give me a solid yes or no) if this issue is fixed, I will close the issue and actually release a new version fixing this bug (and the other one if it's fixed).

**Comment by LemonLake** [comment] 2015-05-30 13:45
Will update the server tonight and get back to you.

**Comment by abdullamu** [comment] 2015-05-30 15:29
i can confirm that both issues were solved no spam and the setting are not resting anymore 

thank you so much im really happy now that i dont need to visit every place i placed the torch on and set the setting for it over and over :)

**Comment by sci4me** [comment] 2015-05-30 20:28
good. i'll close the issue and release an update.

**Closed by sci4me** 2015-05-30 20:28 UTC
